/*
 * Copyright 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was created using the `create_project.py` script located in the
 * `<AndroidX root>/development/project-creator` directory.
 *
 * Please use that script when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import androidx.build.JetbrainsAndroidXPlugin
import androidx.build.LibraryType
import androidx.build.AndroidXComposePlugin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("AndroidXPlugin")
    id("com.android.library")
    id("AndroidXComposePlugin")
    id("JetbrainsAndroidXPlugin")
}

AndroidXComposePlugin.applyAndConfigureKotlinPlugin(project)
JetbrainsAndroidXPlugin.applyAndConfigure(project)

androidXComposeMultiplatform {
    android()
    desktop()
    darwin()
    js()
    wasm()
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":compose:foundation:foundation"))
                api(project(":compose:ui:ui"))
                api(project(":compose:ui:ui-text"))
                api(project(":compose:runtime:runtime"))

                implementation(libs.kotlinStdlib)
                implementation(project(":compose:animation:animation"))
                implementation("org.jetbrains.compose.material:material-icons-core:1.6.11") {
                    // exclude dependencies, because they override local projects when we build 0.0.0-* version
                    // (see https://repo1.maven.org/maven2/org/jetbrains/compose/material/material-icons-core-desktop/1.6.11/material-icons-core-desktop-1.6.11.module)
                    exclude group: "org.jetbrains.compose.ui"
                }
                implementation(project(":compose:material:material-ripple"))
                implementation(project(":compose:ui:ui-util"))
                implementation(project(":wear:compose:compose-foundation"))
            }
        }

        androidMain {
            dependencies {
                implementation("androidx.profileinstaller:profileinstaller:1.4.0")
            }
        }

        androidInstrumentedTest {
            dependencies {
                implementation(project(":compose:ui:ui-test"))
                implementation(project(":compose:ui:ui-test-junit4"))
                implementation(project(":compose:test-utils"))

                implementation(androidxArtifact(":test:screenshot:screenshot"))
                implementation(libs.testRunner)
                implementation(libs.truth)
            }
        }

        androidTest {
            dependencies {
                implementation(libs.testRules)
                implementation(libs.testRunner)
                implementation(libs.junit)
            }
        }

        skikoMain.dependsOn(commonMain)
        desktopMain.dependsOn(skikoMain)
        nonJvmMain.dependsOn(skikoMain)
        webMain.dependsOn(nonJvmMain)
        jsMain.dependsOn(webMain)
        wasmJsMain.dependsOn(webMain)
        nativeMain.dependsOn(nonJvmMain)

        skikoTest.dependsOn(commonTest)
        desktopTest.dependsOn(skikoTest)
        nonJvmTest.dependsOn(skikoTest)
        webTest.dependsOn(nonJvmTest)
        jsTest.dependsOn(webTest)
        wasmJsTest.dependsOn(webTest)
        nativeTest.dependsOn(nonJvmTest)
    }
}

android {
    defaultConfig {
        minSdkVersion 25
    }
    // Use Robolectric 4.+
    testOptions.unitTests.includeAndroidResources = true
    sourceSets.androidTest.assets.srcDirs +=
            project.rootDir.absolutePath + "/../../golden/wear/compose/materialcore"
    buildTypes.configureEach {
        consumerProguardFiles("proguard-rules.pro")
    }
    namespace "androidx.wear.compose.material.core"
}

androidx {
    name = "Android Wear Compose Material Core"
    type = LibraryType.PUBLISHED_LIBRARY
    inceptionYear = "2022"
    description = "WearOS Compose Material Core Library. This library contains themeless " +
            "components that are shared between different WearOS Compose Material libraries. It " +
            "builds upon the Jetpack Compose libraries."
    legacyDisableKotlinStrictApiMode = true
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-Xjvm-default=all",
        ]
    }
}
