/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was created using the `create_project.py` script located in the
 * `<AndroidX root>/development/project-creator` directory.
 *
 * Please use that script when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */

import androidx.build.AndroidXComposePlugin
import androidx.build.JetbrainsAndroidXPlugin
import androidx.build.LibraryType
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("AndroidXPlugin")
    id("com.android.library")
    id("AndroidXComposePlugin")
    id("JetbrainsAndroidXPlugin")
    id("kotlinx-atomicfu")
}

AndroidXComposePlugin.applyAndConfigureKotlinPlugin(project)
JetbrainsAndroidXPlugin.applyAndConfigure(project)

androidXComposeMultiplatform {
    android()
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":compose:foundation:foundation"))
                api(project(":compose:runtime:runtime"))
                api(project(":compose:ui:ui"))
                api(project(":compose:ui:ui-text"))
                api(project(":wear:compose:compose-foundation"))

                implementation(libs.kotlinCoroutinesCore)
                implementation(project(":compose:animation:animation"))
                implementation("org.jetbrains.compose.material:material-icons-core:1.6.11") {
                    // exclude dependencies, because they override local projects when we build 0.0.0-* version
                    // (see https://repo1.maven.org/maven2/org/jetbrains/compose/material/material-icons-core-desktop/1.6.11/material-icons-core-desktop-1.6.11.module)
                    exclude group: "org.jetbrains.compose.ui"
                }
                implementation(project(":compose:material:material-ripple"))
                implementation(project(":compose:ui:ui-util"))
                implementation(project(":wear:compose:compose-material-core"))
                implementation(project(":graphics:graphics-shapes"))
                implementation(project(":compose:animation:animation-graphics"))

                implementation(libs.atomicFu)
                implementation(project(":annotation:annotation"))
            }
        }

        androidMain {
            dependencies {
                implementation("androidx.core:core:1.15.0")
                implementation("androidx.profileinstaller:profileinstaller:1.4.0")

                // Include the wear-sdk jar
                compileOnly files("../../wear_sdk/wear-sdk.jar")
            }
        }

        androidInstrumentedTest {
            dependencies {
                implementation(project(":compose:ui:ui-test"))
                implementation(project(":compose:ui:ui-test-junit4"))
                implementation(project(":compose:test-utils"))
                implementation(androidxArtifact(":test:screenshot:screenshot"))
                implementation(libs.testParameterInjector)
                implementation(libs.testRunner)
                implementation(libs.truth)
                implementation(androidxArtifact(":wear:compose:compose-material3-samples"))
                implementation(libs.leakcanary)
                implementation(libs.leakcanaryInstrumentation)
            }
        }

        androidTest {
            dependencies {
                implementation(libs.testRules)
                implementation(libs.testRunner)
                implementation(libs.junit)

                // Include the wear-sdk jar
                implementation(files("../../wear_sdk/wear-sdk.jar"))
            }
        }

        skikoMain.dependsOn(commonMain)
        desktopMain.dependsOn(skikoMain)
        nonJvmMain.dependsOn(skikoMain)
        webMain.dependsOn(nonJvmMain)
        jsMain.dependsOn(webMain)
        wasmJsMain.dependsOn(webMain)
        nativeMain.dependsOn(nonJvmMain)

        skikoTest.dependsOn(commonTest)
        desktopTest.dependsOn(skikoTest)
        nonJvmTest.dependsOn(skikoTest)
        webTest.dependsOn(nonJvmTest)
        jsTest.dependsOn(webTest)
        wasmJsTest.dependsOn(webTest)
        nativeTest.dependsOn(nonJvmTest)

        commonTest.dependencies {
            implementation(kotlin("test"))
        }

        desktopTest.dependencies {
            implementation(libs.truth)
            implementation(libs.junit)
        }
    }
}

// This task updates the translations of the localizable strings in this module.
// It obtains them from Android's base repository.
tasks.register("updateTranslations", UpdateTranslationsTask.class) {
    group = "localization"
    gitRepo = "https://github.com/androidx/androidx"
    repoResDirectories = [
            "wear/compose/compose-material3/src/main/res"
    ]
    targetDirectory = project.file("src/skikoMain/kotlin/androidx/wear/compose/material3/l10n")
    targetPackageName = "androidx.wear.compose.material3.l10n"
    kotlinStringsPackageName = "androidx.wear.compose.material3.internal"
    stringByResourceName = [
            "wear_m3c_slider_decrease_content_description": "SliderDecreaseIconContentDescription",
            "wear_m3c_slider_increase_content_description": "SliderIncreaseIconContentDescription",
            "wear_m3c_alert_dialog_content_description_confirm_button": "AlertDialogContentDescriptionConfirmButton",
            "wear_m3c_alert_dialog_content_description_dismiss_button": "AlertDialogContentDescriptionDismissButton",
            "wear_m3c_open_on_phone_icon_content_description": "OpenOnPhoneContentDescriptionIcon",
    ]
    // This is all the locales translated by Compose on Android in the ui module:
    // https://github.com/androidx/androidx/tree/androidx-main/wear/compose/compose-material3/src/main/res
    // with the exception of
    // - b+sr+Latn which doesn't appear to be supported by Java
    // - en_XC which has weird invisible LRM characters, and the visible text is the same as for
    //   en anyway.
    locales = [
            "en", "af", "am", "ar", "as", "az", "be", "bg", "bn", "bs", "ca", "cs", "da", "de",
            "el", "en_AU", "en_CA", "en_GB", "en_IN", "es", "es_US", "et", "eu", "fa",
            "fi", "fr", "fr_CA", "gl", "gu", "hi", "hr", "hu", "hy", "in", "is", "it", "iw",
            "ja", "ka", "kk", "km", "kn", "ko", "ky", "lo", "lt", "lv", "mk", "ml", "mn", "mr",
            "ms", "my", "nb", "ne", "nl", "or", "pa", "pl", "pt", "pt_BR", "pt_PT", "ro", "ru",
            "si", "sk", "sl", "sq", "sr", "sv", "sw", "ta", "te", "th", "tl", "tr", "uk", "ur",
            "uz", "vi", "zh_CN", "zh_HK", "zh_TW", "zu"
    ]
}

android {
    defaultConfig {
        minSdk = 25
    }
    buildTypes.configureEach {
        consumerProguardFiles("proguard-rules.pro")
    }
    testOptions.unitTests.returnDefaultValues = true
    namespace = "androidx.wear.compose.material3"
}

androidx {
    name = "Android Wear Compose Material 3"
    type = LibraryType.PUBLISHED_LIBRARY
    inceptionYear = "2022"
    description = "WearOS Compose Material 3 Library. This library makes it easier for " +
            "developers to write Jetpack Compose applications for Wearable devices that " +
            "implement Wear Material 3 Design UX guidelines and specifications. It builds upon " +
            "the Jetpack Compose libraries."
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-Xjvm-default=all",
        ]
    }
}
